### ISSUE TITLE
Installed using pip but still not available

### ISSUE THREAD

**Issue by echo66** [scikit-learn-contrib/polylearn#14]
Greetings!

I've installed this package using pip3. It is listed in the installed packages but, when I try to import it `polylearn`, I get `ModuleNotFoundError: No module named 'polylearn'`

**Comment by echo66** [comment]
So, it seems that I need to download this package and install it manually. I got it wrong.

**Comment by vene** [comment]
I'm happy to hear it worked for you, but `pip install` is supposed to work too. Make sure that the `pip3` and `python3` binaries you are using correspond to one another; ideally use a virtualenv.
