### ISSUE TITLE
cannot import name 'FactorizationMachineClassifier'

### ISSUE THREAD

**Issue by mglowacki100** [scikit-learn-contrib/polylearn#6]
Hi,
I'm new to Python, so it could problem with my lack of knowledge, but:
I've installed polylearn (git ... etc.), now line:
`from polylearn import FactorizationMachineClassifier`
results in error:
`cannot import name 'FactorizationMachineClassifier'` 
I'm using Spyder and Python 3.5.2 |Anaconda 4.1.1 (64-bit).
I've tried to use Python2.7, but I got `ImportError: no module named polylearn' ...
So I don't know, is it a problem with polylearn or I missed some steps.

**Comment by hlin117** [comment]
Hi @mglowacki100. Did you follow the steps [here](https://github.com/scikit-learn-contrib/polylearn/#installation)?

**Comment by mglowacki100** [comment]
Yes. I've attached result of installation "> poly.txt". 
Maybe I'm missing something but it looks ok.
[poly.txt](https://github.com/scikit-learn-contrib/polylearn/files/459999/poly.txt)

**Comment by hlin117** [comment]
Here're some troubleshooting tips:

* If you're using `Spyder`, are you using the correct python binary? (This is most likely your problem.)
* Does `pip show polylearn` do anything? If not, then follow the installation steps again.
* Are you in a virtual environment?

I've never used Anaconda, so unfortunately I can't give you guidance about it.

**Comment by mblondel** [comment]
The logs seem to indicate that the install went fine. Could you run `python` from the command line and try to import polylearn? As @hlin117 mentioned, Spyder might be using a different python binary.

@hlin117 polylearn is not on pip or conda yet.

**Comment by hlin117** [comment]
@mblondel For some reason, I actually get some output with `pip show polylearn`

```
$ pip show polylearn
---
Metadata-Version: 1.1
Name: polylearn
Version: 0.1.dev0
Summary: Factorization machines and polynomial networks for classification and regression in Python.
Home-page: https://contrib.scikit-learn.org/polylearn
Author: Vlad Niculae
Author-email: vlad@vene.ro
License: Simplified BSD
Location: /usr/local/lib/python2.7/site-packages/polylearn-0.1.dev0-py2.7-macosx-10.11-x86_64.egg
Requires:
```

I was pleasantly surprised.

**Comment by mglowacki100** [comment]
`pip show polylearn` shows nothing.
I'll try to do it on clean python. Btw. I have almost the same problem with py-earth.
Lightning works ok, but it uses pip. 
1. When do you plan to put polylearn on pip?
2. To make sure: polylearn works on python 3.5 or only on 2.7?

**Comment by mglowacki100** [comment]
After some googling about import, I've managed to import FactorizationMachineClassifier under python3.5/conda. 
It's ugly, but it seems to work:
`from setuptools import setup`
`from Cython.Build import cythonize`
`import pyximport`
`pyximport.install()`
`import sys`
`sys.path.append('/home/mglowacki/Desktop/polylearn')`
`sys.path.append('/home/mglowacki/Desktop/polylearn/polylearn')`

**Comment by hlin117** [comment]
@mglowacki100 With all due respect, I don't think that this is a Polylearn bug, and that this issue could be closed. It seems that when you installed Polylearn, but it only works with Python 2.7 and not Python 3.5. Python 2 is the default on most systems, which would explain why the package did not install for Python 3.

**Comment by hlin117** [comment]
You might want to try the following installation steps:

```
git clone https://github.com/scikit-learn-contrib/polylearn.git
cd polylearn
python3 setup.py build
sudo python3 setup.py install
```

Assuming that `which python3` is linked to your Python 3 path.

**Comment by hlin117** [comment]
By the way:
> 2. To make sure: polylearn works on python 3.5 or only on 2.7?
According to [Travis](https://travis-ci.org/scikit-learn-contrib/polylearn) (the continuous integration testing tool), unit tests pass on both Python 2.7 and Python 3.5. So, everything (fingers crossed) that works on Python 2.7 should also work on Python 3.5.

**Comment by mglowacki100** [comment]
Thanks for help.
