### ISSUE TITLE
Difficulty importing lightning correctly in polylearn

### ISSUE THREAD

**Issue by hlin117** [scikit-learn-contrib/polylearn#7]
I followed the installation steps [here](https://github.com/scikit-learn-contrib/polylearn#installation), and after installed lightning-python 1.2.1. (`pip install lightning-python`.) However I'm getting this error

```
>>> import polylearn
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/polylearn-0.1.dev0-py2.7-macosx-10.11-x86_64.egg/polylearn/__init__.py", line 1, in <module>
    from .factorization_machine import FactorizationMachineRegressor
  File "/usr/local/lib/python2.7/site-packages/polylearn-0.1.dev0-py2.7-macosx-10.11-x86_64.egg/polylearn/factorization_machine.py", line 22, in <module>
    from lightning.impl.dataset_fast import get_dataset
ImportError: No module named impl.dataset_fast
```

I'm using python 2.7.12 on OS X. It might be worth specifying which version of lightning to install.

Marginally related: #6

**Comment by mblondel** [comment]
`lightning-python` is a different project. You need to install `sklearn-contrib-lightning`.

Perhaps the README file should give the pip and conda command lines for installing the dependencies.

**Comment by hlin117** [comment]
@mblondel Works fine now =]

I do agree that it would be nice to disambiguate `lightning-python` and `sklearn-contrib-lightning` though.

**Comment by javadba** [comment]
Same problem here. This is very confusing and unexpected.. Second the motion to document this.

**Comment by vene** [comment]
On February 26, 2017 12:51:37 PM GMT+09:00, StephenBoesch <notifications@github.com> wrote:
>Same problem here. This is very confusing and unexpected.. Second the
>motion to document this.

Fully agree, I'll add a note.

I was also thinking we could merge the functionality needed from lightning, since it's just one file. Would you like to submit a pull request for that?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by javadba** [comment]
ah ok will take a look

2017-02-25 22:15 GMT-08:00 Vlad Niculae <notifications@github.com>:

> On February 26, 2017 12:51:37 PM GMT+09:00, StephenBoesch <

**Comment by vene** [comment]
The website and readme should be clearer now, does the change look satisfying?

**Comment by hlin117** [comment]
Cool. Thanks @vene!
